### ISSUE TITLE
Change from dot delimiter to slash delimiter

### ISSUE THREAD

**Issue by UlfBj** [GENIVI/vehicle_signal_specification#117]
Using slash (/) as delimiter instead of dot (.) enables direct use of the VSS path in URIs. E. g. in the case of using HTTP as the transport protocol for communication of VSS data, the VSS path naturally becomes a part of the URL. According to the RFC 2396 the path component of a URI must not include the dot character, and the de-facto delimiter for URI path segments is of course the slash.

**Comment by danielwilms** [comment]
decision: keep dot notation
