### ISSUE TITLE
Update Release process

### ISSUE THREAD

**Issue by danielwilms** [GENIVI/vehicle_signal_specification#140]
Release process is outdated and needs an update.

**Comment by gunnarx** [comment]
My proposal for a working process is that there is no need to create an "Issue" if the PR can explain the problem directly.  Such as in this case, there is no waiting for discussion before the PR is created.  
So it just becomes like two duplicate things for the same thing?  I.e. only the PR would be enough for me if no longer discussion is expected.

**Comment by danielwilms** [comment]
Now, I addressed it immediately, so in this case you're right. But in general I think it is as well a way to organise work and to have a backlog. Not necessarily for discussion only.

**Comment by danielwilms** [comment]
Now, I addressed it immediately, so in this case you're right. But in general I think it is as well a way to organise work and to have a backlog. Not necessarily for discussion only.
