### ISSUE TITLE
Validation of singal types and associated error handling

### ISSUE THREAD

**Issue by vivekgalatage** [GENIVI/vehicle_signal_specification#15]
Hi,

Is there any specification describing the error handling and relaying of error information back to the client?

e.g. as per the vehicle signal specification, the `Cabin.HVAC.IsFrontDefrosterActive` is a `boolean`. And if the client sends the data as

```json
{
    "action": "set",
    "path": "Cabin.HVAC.IsFrontDefrosterActive",
    "value": 1
}
```

In this case the value is an integer (1) while the expected value is `boolean`. So the server should respond with an error back to the client.

Is there any documentation which states this?

**Comment by rstreif** [comment]
@vivekgalatage This is only a specification of the vehicle signals. An actual server implementation would have to deal with such issues and either be tolerant of it (if possible which could be the case for this example) of indicate an error to the client.
