### ISSUE TITLE
Clarify handling of generated files

### ISSUE THREAD

**Issue by gunnarx** [GENIVI/vehicle_signal_specification#153]
In the repo we can see a few **files that are generated** from the original files that are located under **spec/\***

* [vss_rel_2.0.0-alpha%2B006.csv](https://github.com/GENIVI/vehicle_signal_specification/blob/master/vss_rel_2.0.0-alpha%2B006.csv)
* [VehicleSignalSpecification.vspec](https://github.com/GENIVI/vehicle_signal_specification/blob/master/spec/VehicleSignalSpecification.vspec)

It is always a balance of these things:

1) The general best practice is of course always to have one source of truth, and this means as a principle generated files are not placed into version control (because they risk being out of date, and because it is redundant information)
but also:
2) Usefulness of the file in question - for example it can be very convenient to just point to content on the web for review.

And in [this discussion, W3C automotive #324](https://github.com/w3c/automotive/pull/324#issuecomment-611529193) it was requested to point to a **single file** specification.  

#152 is yet another example, where the original files are changed, but not the generated files.  How should we handle such PRs?  Is it expected that the PR should include an update of the corresponding generated files?

**Questions**

Question 1) Is it possible and desirable to have a single-file version of VSS that is "official".  How would we manage that in relation to the individual source files under spec/*
Question 2) Shall we remove generated files (immediately I would propose *.csv) and inform users how to build them?

**Options**

- Remove generated files, update documentation to make it clear how to reproduce
- Add generated files under a clearly marked directory and clearly designating that those are only useful examples and not the official source.
- Produce generated files as part of a tagged release (thus I think fulfilling the request in [W3C #324](https://github.com/w3c/automotive/pull/324#issuecomment-611529193))

**Comment by danielwilms** [comment]
CI to build the files and point from the README to it (e.g. latest).
* daily build (e.g. with travis)
* easily accessible link
@danielwilms looks into it.
For release:
* snapshot of documentation

All generated files will be removed later.
