### ISSUE TITLE
The signal `isAirConditioningActive` should be renamed to `IsAirConditioningActive`

### ISSUE THREAD

**Issue by vivekgalatage** [GENIVI/vehicle_signal_specification#16]
The signal `Cabin.HVAC.isAirConditioningActive` should be renamed to `Cabin.HVAC.IsAirConditioningActive` to be consistent with other names.

The signal is having small case letter `i` instead of capital letter `I`

**Comment by rstreif** [comment]
@vivekgalatage Thank you for noticing that and notifying us about it. Fixed in #17.
