### ISSUE TITLE
Add some properties to ElectricMotor.vspec

### ISSUE THREAD

**Issue by dakrbo** [GENIVI/vehicle_signal_specification#172]
Hi all - to get going with the freshly restructured Powertrain branch, I added an initial bunch of properties to the (previously empty) ElectricMotor.vspec

- MaxPower
- MaxTorque
- MaxRegenPower
- MaxRegenTorque
- Motor
- Motor.Speed
- Motor.Temperature:
- Motor.CoolantTemperature
- Motor.Power
- Motor.Torque

(pull request #171 )

**Comment by danielwilms** [comment]
Let's take the discussion on the PR #171
