### ISSUE TITLE
Package is not installable from pip via local directory

### ISSUE THREAD

**Issue by rfrowe** [GENIVI/vehicle_signal_specification#174]
## Description
The Python package in this repo is not installable with pip when installing from a cloned repository.

## Expected
The following should work:
```bash
git clone git@github.com:GENIVI/vehicle_signal_specification.git
pip install ./vehicle_signal_specification/vss-tools
```

This makes it impossible to include the specification as a submodule and install the Python package from the local directory via pip, `requirements.txt`, `setup.py`, `setup.cfg`, or `Pipfile`, thus necessitating either another clone to install via git, rather than local directory, or manually calling `setup.py`.

## Actual
```pytb
FileNotFoundError: [Errno 2] No such file or directory: '../VERSION'
```

## Cause
When pip installs from a local directory, it copies the directory in question (here: `vehicle_signal_specification/vss-tools`) to a temporary directory. Obviously, this does not include `../VERSION` as it is in the parent directory. The installation then fails as a result of GENIVI/vss-tools#9.

## Solution
Same as GENIVI/vss-tools#9

**Comment by danielwilms** [comment]
Discussion in the tools repository. If closing is misunderstanding, please reopen.
