### ISSUE TITLE
vss-tools/vspec.py does not import sys

### ISSUE THREAD

**Issue by rfrowe** [GENIVI/vehicle_signal_specification#175]
This causes GENIVI/vss-tools#10

## Solution
Update submodule

**Comment by gunnarx** [comment]
Closed here and opened in GENIVI/vss-tools#10

**Comment by gunnarx** [comment]
Sorry for confusing all of this.  I didn't read this ticket properly.  Updating the submodule in this repository is correct.   I am currently however blocked from doing that by https://github.com/GENIVI/vss-tools/issues/11

**Comment by danielwilms** [comment]
@rfrowe, @gunnarx There are some fixes to be merged, like [PR#16](../../vss-tools/pull/16), [PR#17](../../vss-tools/pull/17). Then I'd update the submodule.

**Comment by danielwilms** [comment]
Can be closed: #184
