### ISSUE TITLE
Signal for ignition/key state

### ISSUE THREAD

**Issue by rfrowe** [GENIVI/vehicle_signal_specification#179]
I would like the ability to determine, via VSS, the current ignition/engine state of the car. As far as I can tell, there is no such signal. The closest would be `Vehicle.IgnitionOnTime`, however one must compare two successive signals to determine if the ignition is on.

I propose adding an `IgnitionOn` boolean or some kind of `KeyState` which would be one of `[ON, ACC, OFF]` which would also suffice for my purposes. I'm happy to implement this in the spec, but I'm interested to here thoughts on this signal addition and under which node it should live.

**Comment by danielwilms** [comment]
> I propose adding an IgnitionOn boolean or some kind of KeyState which would be one of [ON, ACC, OFF] which would also suffice for my purposes

I think a signal like that is indeed missing. Would rather see the boolean, as something like ACC I'd see in ADAS.

**Comment by rfrowe** [comment]
@danielwilms Implemented in #182
