### ISSUE TITLE
Reduce hierarchy levels in Powertrain subtree

### ISSUE THREAD

**Issue by dakrbo** [GENIVI/vehicle_signal_specification#187]
Hi all, picking up on [this comment](https://github.com/GENIVI/vehicle_signal_specification/issues/167#issuecomment-668714144) from @gunnarx , I propose to remove the 'EnergyStorage' and 'PowerSource' branches within the Powertrain subtree - move every <component>.vspec directly into the Powertrain component.

This would also make it simpler to decide where to place things like a "FossilEvHybrid.vspec" definition.

**Comment by danielwilms** [comment]
Fixed in #190
