### ISSUE TITLE
Unknown "type" Int16 for Chassis.vspec

### ISSUE THREAD

**Issue by zubairhamed** [GENIVI/vehicle_signal_specification#192]
Multiple type values have incorrect values. Perhaps a typo for datatype instead. 

https://github.com/GENIVI/vehicle_signal_specification/blob/e21f5506eaea04b9ebe278d99ada2360c2c6a046/spec/Private/CARFIT/Chassis/Chassis.vspec

https://github.com/GENIVI/vehicle_signal_specification/blob/e21f5506eaea04b9ebe278d99ada2360c2c6a046/spec/Private/CARFIT/Chassis/Wheel.vspec

**Comment by danielwilms** [comment]
@zubairhamed, the private branch is currently not maintained. We should discuss on how to move forward with the signals, which are specified there.

**Comment by danielwilms** [comment]
remove private branch for 2.0 or see if it makes sense

**Comment by danielwilms** [comment]
fixed in #212
