### ISSUE TITLE
Changing Vehicle.Speed and Accelerations to float without limitations

### ISSUE THREAD

**Issue by chheis** [GENIVI/vehicle_signal_specification#228]
Due to calculation loses (some function may use m/s internally). Would be better to have more accuracy for the speed.
https://github.com/GENIVI/vehicle_signal_specification/blob/master/spec/Vehicle/Vehicle.vspec 
And also to change the vehicle acceleration to float:
Acceleration.Longitudinal / Acceleration.Lateral / Acceleration.Vertical

**Comment by erikbosch** [comment]
Do we have any general approach on when to use float/double and when to use integer types? We currently have a large number of datapoints where we use integer-representation, where someone maybe wants to have more precision in the future.  Check e.g. all temperature datapoints where it seems to be quite random whether we use integer or float.  

By the way, OBD.Speed already use float and without the -250/+250 limits

**Comment by danielwilms** [comment]
1. Change speed to float. 
2. @chheis create issue number vs int/float
3. @erikbosch list of questionable integer

**Comment by erikbosch** [comment]
I have identified some units (e.g. cm, l, km/h, celsius, inch, degrees/s, m/s^2) where int as I see it isn't sufficient. But float (or in rare cases double) can as I see it be considered for all datapoints where a unit is specified.

Suggestion: If we consider it reasonable to change at least the units above to float I could create separate PRs for each of them. In some cases I suggest that units are changed, but that could be discussed as part of the PRs
