### ISSUE TITLE
Document the aggregate feature (metadata convention for 'deployment' layers)

### ISSUE THREAD

**Issue by gunnarx** [GENIVI/vehicle_signal_specification#256]
The idea of aggregate is a hint to code generators and protocols that the entire branch ought to be transferred atomically.  Example: GPS position should not transfer Lat and Long separately with the risk of one of them being updated in between (race condition).

It was agreed this is rather deployment-model info and should be added in a layer and thus it was removed from the core model in #254.  This ticket is to trigger reintroducing this in the documentation so that it becomes a known convention, to be defined in a layer.

**Comment by danielwilms** [comment]
Documentation updated with #254
