### ISSUE TITLE
Support of arraysize?

### ISSUE THREAD

**Issue by erikbosch** [GENIVI/vehicle_signal_specification#275]
According to https://genivi.github.io/vehicle_signal_specification/rule_set/data_entry/data_types/ a keyword `arraysize` is allowed. But if I try it out (on e.g. `SeatPosCount`) I get the error below.

`Warning: Non-core attribute "arraysize" in elment SeatPosCount found.`

... and it appears that we do not really care about it any of our tools. 

- Do we want to keep supporting it (and change vss-tools accordingly so that it at least does not give an error, but possibly a warning that it is currently ignored)
- Or do we want to remove it from the documentation?

(By the way, `SeatRowCount`/`SeatPosCount` seems to be intended as a solution to the instance handling of `Seat`, by reading those two signals you know which instances of  `Seat` that actually exists)

**Comment by gunnarx** [comment]
We used to have a discussion on this including the idea of this syntax:
```
- type: uint_32[4]
```
but the agreement was:
```
- type: uint_32[]
- arraysize: 4
```
so the tools should be adjusted accordingly.
