### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by ssivasan** [GENIVI/vehicle_signal_specification#28]
Few spelling to be corrected in the below topics.

ATTRIBUTE ENTRY - the "specifiation", that never changes

SIGNAL NAMING CONVENTION - the "reaview" mirror

ATTRIBUTES - data that can be specified when the "bspec" file is installed.

EXTENDING AND OVERRIDING SIGNALS - Fig 4. "Overidden" signals
                                                                     vss_23.vspec and then "oveerriding" the

The Quoted item needs correction.

**Comment by rstreif** [comment]
@ssivasan 

Thank you for submitting these corrections. I am not sure if you are familiar with the GitHub contribution process. I would like to ask you to simply make the corrections and submit a pull request for me to merge. Thank you.

**Comment by ssivasan** [comment]
I have submitted a pull request with commit ID - 73a9ad8. Thanks.
