### ISSUE TITLE
Travis builds of uploaded PRs not working

### ISSUE THREAD

**Issue by erikbosch** [GENIVI/vehicle_signal_specification#299]
Seems our travis-setup for build of PRs are not working any longer. Possibly related to this announced change:

"Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on. "

https://travis-ci.org/github/GENIVI/vehicle_signal_specification/pull_requests
https://travis-ci.com/github/GENIVI/vss-tools/pull_requests

**Comment by danielwilms** [comment]
fixed with github actions. keep as reminder for removing travis files, if github actions more reliable
