### ISSUE TITLE
https://github.com/GENIVI/vehicle_signal_specification/issues/1#sysdav-138844175

### ISSUE THREAD

**Issue by Payaspx** [GENIVI/vehicle_signal_specification#320]
https://github.com/GENIVI/vehicle_signal_specification/issues/1#issue-138844175

_Originally posted by @Payaspx in https://github.com/GENIVI/vehicle_signal_specification/issues/1#issuecomment-895510068_

**Comment by erikbosch** [comment]
@Payaspx - you commented an old closed issue, and created a new one, but it is difficult to know what you want. Could you elaborate, or was this one created by mistake

**Comment by gunnarx** [comment]
Inappropriate issue format.  In any case the comment has been answered (again) on issue #1.  If there is still anything unclear, please clarify what is unclear.
