### ISSUE TITLE
Default value behavior for arrays

### ISSUE THREAD

**Issue by crea7or** [GENIVI/vehicle_signal_specification#329]
If datatype is specified as an array of some types, why default value is not an array, even if it's a single element?  Maybe this is an typo, but documentation isn't clear in this case too. 

example from generated json:

```json
"SeatPosCount": {
            "datatype": "uint8[]",
            "default": 0,
            "description": "Number of seats across each row from the front to the rear",
            "type": "attribute",
            "uuid": "8dd40ecd47ab51c79ed9c74ae4296d7e"
          }
```

**Comment by erikbosch** [comment]
I think this is a typo/regression introduced in https://github.com/GENIVI/vehicle_signal_specification/commit/2714a7a0d156aa12ffd38bdf5c418241e1f1ec7a 

One can argue that the default value shall be removed from the VSS-spec as that must be specified for each vehicle on "layer" level. But still - an interesting question how a default value for an array shall be expressed on "layer" level. Should it e.g. be defined as `[2, 3]` for a standard car with 2 seats in the front row and 3 in the back row?

**Comment by crea7or** [comment]
Currently we are trying to transfer some non-can related configs to vss (because it's suitable for it) and default values is a must have. Maybe a tag name is not a very good since attributes should have just read-only "value", but vss allow to change them so it's ok.

**Comment by danielwilms** [comment]
@erikbosch, make proposal for documentation.
