### ISSUE TITLE
Boolean or String

### ISSUE THREAD

**Issue by iamsanjeev** [GENIVI/vehicle_signal_specification#36]
Signal.Body.Windshield.Front.Heater.Status	
Front windshield heater status	
String : off on NA

Can we make this a Boolean ?

**Comment by rstreif** [comment]
@iamsanjeev Yes, this should be boolean.

**Comment by iamsanjeev** [comment]
@rstreif https://github.com/GENIVI/vehicle_signal_specification/pull/37
