### ISSUE TITLE
Spelling error: DriverPostion

### ISSUE THREAD

**Issue by erikbosch** [GENIVI/vehicle_signal_specification#40]
I assume it should be called DriverPosition. 

Furthermore, I am not 100% sure that I understand this variable correctly? Should it be interpreted as seat number from left?

https://github.com/GENIVI/vehicle_signal_specification/blob/222bbc6d1900e2c82dc15138da2266dcdae3c53e/vss_rel_1.0.fidl#L306

**Comment by gunnarx** [comment]
Please provide PRs if possible.  Anyway, easy fix so I pushed this and a few things in a PR (see ref above)

**Comment by erikbosch** [comment]
Thanks for creating the PR Gunnar

**Comment by rstreif** [comment]
Fixed with #55.
