### ISSUE TITLE
Transmission Drive Type  enum:  abbreviation not really clear “fwd”, “rwd”

### ISSUE THREAD

**Issue by Geraldbosch** [GENIVI/vehicle_signal_specification#46]

**Comment by gunnarx** [comment]
File, and line, please

**Comment by gunnarx** [comment]
I assume it's fwd = forward wheel drive, rwd = rear whell drive, awd = all wheel drive.
Should there be a comment to clarify?  Please suggest a change through PR.

**Comment by klotzbenjamin** [comment]
In https://github.com/GENIVI/vehicle_signal_specification/blob/master/spec/Drivetrain/Transmission.vspec, it has been corected already:

`- DriveType:`
`  datatype: string`
`  type: attribute`
`  enum: [ "unknown", "forward wheel drive", "rear wheel drive", "all wheel drive" ]`
`  value: "unknown"`
`  description: Drive type.`

@danielwilms we can close this issue.

**Comment by danielwilms** [comment]
Hi @klotzbenjamin, great. There's one open question for me: Do we have a common way to define enums? The spaces look weird.

**Comment by klotzbenjamin** [comment]
> Do we have a common way to define enums? The spaces look weird.

I do not see any rule for defining enums, in this case the only rule is that the elements from the enum are of `datatype: string`.

**Comment by danielwilms** [comment]
OK, I'll close this one then and open a new one for uniform enum definition.
