### ISSUE TITLE
Branch policy?

### ISSUE THREAD

**Issue by gunnarx** [GENIVI/vehicle_signal_specification#54]
@rstreif What's the branch policy?

**develop** is way ahead of **master**, which has not been updated since 2016.  
Not sure what **master** is for now.  I'd suggest simply merging **develop** into **master** (it's a fast forward) and then delete **develop** and keep **master**.  OK?

**Comment by gunnarx** [comment]
Bump.  Maybe we can discuss it today?

**Comment by rstreif** [comment]
Merge `develop` into `master`.

**Comment by gunnarx** [comment]
As agreed, I will do this change.

**Comment by gunnarx** [comment]
* merged develop into master (fast forward) and pushed.  
* Changed settings in GitHub for the repo such that master is now the default branch
* develop has been deleted
