### ISSUE TITLE
Duplicate SteeringWheel branch

### ISSUE THREAD

**Issue by klotzbenjamin** [GENIVI/vehicle_signal_specification#59]
Hi,

I have noticed 2 branches called Steering Wheel:

- Attribute.Cabin.SteeringWheel: https://github.com/GENIVI/vehicle_signal_specification/blob/develop/spec/Attribute/Cabin.vspec which contains the attrobute of the position of the steering wheel
- Signal.Chassis.SteeringWheel: https://github.com/GENIVI/vehicle_signal_specification/blob/develop/spec/Signal/Chassis/Chassis.vspec which contains the angle/tilt/extension of the steering wheel.

I believe these 2 branches should be merged as they represent the same part of the vehicle, and it should be under the "Cabin" branch.

**Comment by gunnarx** [comment]
A few weeks ago the EG-NW group discussed and decided to fold the develop branch into master so the above links no longer work. Updated links: [Cabin.vspec](https://github.com/GENIVI/vehicle_signal_specification/blob/master/spec/Attribute/Cabin.vspec), [Chassis.vspec](https://github.com/GENIVI/vehicle_signal_specification/blob/master/spec/Signal/Chassis/Chassis.vspec)
