### ISSUE TITLE
Lacking description of the signal Id database file

### ISSUE THREAD

**Issue by peterMelco** [GENIVI/vehicle_signal_specification#7]
There seem not be a description on the Signal DB file format, which results in an error and that the id is assigned -1 :

**NO SIGNAL DB FILE TO USE!**

 {

  "Vehicle": {
    "type": "branch", 
    "children": {
      "VehicleConfiguration": {

**Comment by rstreif** [comment]
@peterMelco Could you please elaborate under what circumstances you have gotten that error? The signal ID database file is used by VSI to index the signals for faster lookup (it could be used by others too of course).

**Comment by PeterWinzell** [comment]
Again I need to get back to this...

**Comment by PeterWinzell** [comment]
This can be closed .
