### ISSUE TITLE
Datatype names are inconsistent

### ISSUE THREAD

**Issue by rai20** [GENIVI/vehicle_signal_specification#86]
Hi,

the datatypes defined in the sample json file (vss_rel_2.0.0-alpha+003.json) is inconsistent. The datatype in some place is Int8 and in other places int8 ( also Uint8 and uint8). Could this be made consistent? Which format is correct?

 "Temperature": {
                "min": -50, 
                "datatype": "Int16", 
                "max": 200, 
                "type": "sensor", 
                "id": 3446, 
                "unit": "celsius", 
                "description": "The current gearbox temperature"
}

EOP": {
                    "description": "Engine oil pressure.", 
                    "min": 0, 
                    "datatype": "int16", 
                    "max": 1000, 
                    "type": "sensor", 
                    "id": 3434, 
                    "unit": "kpa"
}, 

Regards,
Pratheek

**Comment by danielwilms** [comment]
@rai20: could you please check if the PR solves your issue, then I can merge it: https://github.com/GENIVI/vehicle_signal_specification/pull/90/commits/ecd45f69e442b32056999993174f08ef9dc9e817

**Comment by rai20** [comment]
made a quick test and seems to work fine.
Thank you for responding so quickly 👍
